name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
    - name: App Center
      uses: wzieba/AppCenter-Github-Action@v1.3.3
      with:
        appName: ${{ github.event.repository.name }}
        token: 8bf679835fec654a36868a9ef228e87963e0bc0c
        group: .apk
        file:  .zip
